class gergundata {
  ger() {
    List<Map<String, dynamic>> listable = [
      <String, dynamic>{
        "id": 'glock18',
        "name": 'Glock-18',
        "ammunition": '20/120',
        "order": 1,
        "prizeForKilling": 300,
        "damage": 30,
        "firingRate": 6,
        "recoilControl": 83,
        "precisionRange": 22,
        "penetrationInProtection": 94,
      },
      <String, dynamic>{
        "id": 'dualberetas',
        "name": 'Dual Beretas',
        "ammunition": '30/120',
        "order": 2,
        "prizeForKilling": 300,
        "damage": 38,
        "firingRate": 8,
        "recoilControl": 68,
        "precisionRange": 18,
        "penetrationInProtection": 115,
      },
      <String, dynamic>{
        "id": 'p250',
        "name": 'P250',
        "ammunition": '13/26',
        "order": 4,
        "prizeForKilling": 300,
        "damage": 38,
        "firingRate": 6,
        "recoilControl": 70,
        "precisionRange": 15,
        "penetrationInProtection": 128,
      },
      <String, dynamic>{
        "id": 'tec9',
        "name": 'Tec-9',
        "ammunition": '18/90',
        "order": 5,
        "prizeForKilling": 300,
        "damage": 33,
        "firingRate": 8,
        "recoilControl": 74,
        "precisionRange": 24,
        "penetrationInProtection": 181,
      },
      <String, dynamic>{
        "id": 'fiveseven',
        "name": 'Five-SeveN',
        "ammunition": '20/100',
        "order": 6,
        "prizeForKilling": 300,
        "damage": 32,
        "firingRate": 6,
        "recoilControl": 70,
        "precisionRange": 15,
        "penetrationInProtection": 182,
      },
      <String, dynamic>{
        "id": 'deserteagle',
        "name": 'Desert Eagle',
        "ammunition": '7/35',
        "order": 7,
        "prizeForKilling": 300,
        "damage": 53,
        "firingRate": 4,
        "recoilControl": 9,
        "precisionRange": 27,
        "penetrationInProtection": 186,
      },
      <String, dynamic>{
        "id": 'p2000',
        "name": 'P2000',
        "ammunition": '13/52',
        "order": 8,
        "prizeForKilling": 300,
        "damage": 53,
        "firingRate": 5,
        "recoilControl": 73,
        "precisionRange": 24,
        "penetrationInProtection": 101,
      },
    ];
  }
}
